### ISSUE TITLE
Error: SNCERR_INIT Resource problem or gssapi library invalid/missing

### ISSUE THREAD

**Issue by nicolabeghin** [kaduk/osxsnc#2]
# Context
* OSX 10.12 (Monterey) on Apple Silicon M1
* `osxsnc-1.0-final` compiled from scratch and installed in `/usr/local/lib/sncgss.dyld`

# Running SAPGUI
Using SAPGUI 7.70rev4 (latest available release):

    export SNC_LIB=/usr/local/lib/sncgss.dyld
    open ~/Applications/SAP\ Clients/SAPGUI\ 7.70rev4/SAPGUI\ 7.70rev4.app

![image](https://user-images.githubusercontent.com/2743637/153615001-48d511df-9cc4-4836-a022-7a44f0abfeea.png)

# References
https://discussions.apple.com/thread/7716320

Any hint is welcome, thanks a lot!

**Comment by nicolabeghin** [comment]
A workaround for anyone getting to this issue: disable the SNC option in the specific connection and everything should work out if SNC is not mandatory.

![image](https://user-images.githubusercontent.com/2743637/153617165-c552a634-71a3-447c-8f80-350f9c58e01f.png)

**Comment by joshyanand** [comment]
I got the same error after getting a new Mac. Issue was resolved after installing SAP Secure Login Client. On non SAP laptops, I am guessing a similar app is needed.
